name: hris
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.0
  cloud_firestore: ^4.11.0
  http: ^1.5.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.0.7
  provider: ^6.1.1
  image_cropper: ^9.1.0
  table_calendar: ^3.0.9
  # firebase_core: ^2.31.0
  # firebase_auth: ^4.19.0
  # # firebase_core: ^2.24.0
  # cloud_firestore: ^4.13.3  # or firebase_database: ^10.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/2.png
    - assets/3.png
    - assets/kelin.png
    - assets/profile.jpg
    - assets/human-resources_hris.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/kelin.png"
